
package universidad.materia.vistas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import universidad.entidades.Materia;
import universidad.modelo.Conexion;
import universidad.modelo.MateriaData;

/**
 *
 * @author joni
 */
public class MateriaGuardar extends javax.swing.JInternalFrame {

    Conexion c = new Conexion();
    private DefaultTableModel modelo=new DefaultTableModel();
    MateriaData md;
    Materia m;
    
    public MateriaGuardar() {
        initComponents();
        md= new MateriaData(c);
        initComponents();
        //this.setLocation(500, 0);
        Conexion c = new Conexion();
        armaCabeceraTabla();
        modelo.isCellEditable(0, 1);
        this.cargaDatosInscriptas();
        modelo.isCellEditable(0, 1);
        this.setResizable(false);
        //jTableGuardarMateria.getTableHeader().setReorderingAllowed(false) ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGuardarMateria = new javax.swing.JTable();
        jButtonSalir = new javax.swing.JButton();
        jlbtitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        JLabelNombre.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        JLabelNombre.setText("Ingrese Nombre:");

        jTextFieldNombre.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jButtonGuardar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jTableGuardarMateria = new javax.swing.JTable(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTableGuardarMateria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableGuardarMateria.setColumnSelectionAllowed(true);
        jTableGuardarMateria.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableGuardarMateria);

        jButtonSalir.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jlbtitulo.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jlbtitulo.setForeground(new java.awt.Color(255, 0, 0));
        jlbtitulo.setText("Guardar Materia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(JLabelNombre)
                            .addGap(32, 32, 32)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonGuardar))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonSalir)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jlbtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlbtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSalir)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        
        List<Materia> ml = new ArrayList<>();
        ml = md.obtenerMaterias();
        boolean agregar=true;
        for(int i=0;i< ml.size();i++){
            Materia m=ml.get(i);
            if(jTextFieldNombre.getText().equalsIgnoreCase(m.getNombreMateria())|| jTextFieldNombre.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Ya tenemos una materia registrada con el nombre: "+jTextFieldNombre.getText(), "ERROR!", JOptionPane.WARNING_MESSAGE);
                i=ml.size();
                agregar=false;
            } 
        }
        if(agregar){
           int x =JOptionPane.showConfirmDialog(this, "Desea guardar la materia?","ATENCION!!",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
           if(x== JOptionPane.YES_OPTION){
                m = new Materia();
                m.setNombreMateria(jTextFieldNombre.getText());
                md.guardarMateria(m);
                borraFilasTabla();
                cargaDatosInscriptas();
           }
           
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    public void armaCabeceraTabla(){
           //Titulos de Columnas
        ArrayList<Object> columnas=new ArrayList<Object>();
        columnas.add("ID");
        columnas.add("Nombre Materia");
        for(Object it:columnas){
        
            modelo.addColumn(it);
        }
        jTableGuardarMateria.setModel(modelo);
  }
public void borraFilasTabla(){

        int a =modelo.getRowCount()-1;

           for(int i=a;i>=0;i--){
   
                modelo.removeRow(i);
           }
}
public void cargaDatosInscriptas(){
    
        borraFilasTabla();
           //Llenar filas
        
        List<Materia> lista = md.obtenerMaterias();
        
        for(Materia m:lista){
        
            modelo.addRow(new Object[]{m.getIdMateria(),m.getNombreMateria()});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelNombre;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableGuardarMateria;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JLabel jlbtitulo;
    // End of variables declaration//GEN-END:variables
}
