/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidad.inscripcion.vistas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import universidad.modelo.*;
import universidad.entidades.*;
/**
 *
 * @author Alumno
 */
public class InscripcionCalificacionVistas extends javax.swing.JFrame {
    Conexion c = new Conexion();
    AlumnoData ad= new AlumnoData(c);
    MateriaData md= new MateriaData(c);
    InscripcionData id= new InscripcionData(c);
    
    public InscripcionCalificacionVistas() {
        initComponents();
        ArrayList<Inscripcion> arr = new ArrayList<>();
        arr.addAll(id.obtenerInscripcion());
        for(int x=0;x<arr.size();x++){
            String idI=String.valueOf(arr.get(x).getIdInscripcion());
            int a=arr.get(x).getAlumno().getIdAlumno();
            int m=arr.get(x).getMateria().getIdMateria();
            Alumno al=ad.buscarAlumno(a);
            Materia ma=md.buscarMateria(m);
            String cb=idI+"-"+al.getNombreAlumno()+"-"+ma.getNombreMateria();
            CBInscripcion.addItem(cb);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CBInscripcion = new javax.swing.JComboBox<>();
        TXTAlumno = new javax.swing.JTextField();
        TXTMateria = new javax.swing.JTextField();
        TXTCalificacion = new javax.swing.JTextField();
        BCalificacion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TXTIdInscripcion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CBInscripcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inscripcion" }));
        CBInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBInscripcionActionPerformed(evt);
            }
        });

        TXTAlumno.setEditable(false);

        TXTMateria.setEditable(false);

        TXTCalificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTCalificacionKeyTyped(evt);
            }
        });

        BCalificacion.setText("Asignar Nota");
        BCalificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCalificacionActionPerformed(evt);
            }
        });

        jLabel1.setText("Alumno");

        jLabel2.setText("Materia");

        jLabel3.setText("Calificacion");

        jLabel4.setText("IdInscripcion");

        TXTIdInscripcion.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BCalificacion)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TXTAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(TXTIdInscripcion)
                            .addComponent(TXTMateria)
                            .addComponent(TXTCalificacion)))
                    .addComponent(CBInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(CBInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TXTIdInscripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXTAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXTMateria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXTCalificacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(7, 7, 7)
                .addComponent(BCalificacion)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBInscripcionActionPerformed
        // TODO add your handling code here:
        if(CBInscripcion.getSelectedItem().toString().equalsIgnoreCase("Inscripcion")){
            TXTAlumno.setText("");
            TXTMateria.setText("");
            TXTCalificacion.setText("");
        }else{
       String arr[]= CBInscripcion.getSelectedItem().toString().split("-");
       TXTIdInscripcion.setText(arr[0]);
       TXTAlumno.setText(arr[1]);
       TXTMateria.setText(arr[2]);
       int a=Integer.parseInt(arr[0]);
       Inscripcion in=id.buscarInscripcion(a);
       double cal=in.getNota();
       String c=String.valueOf(cal);
       TXTCalificacion.setText(c);
       }
    }//GEN-LAST:event_CBInscripcionActionPerformed

    private void BCalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCalificacionActionPerformed
        // TODO add your handling code here:
       double n=Double.parseDouble(TXTCalificacion.getText());
        if(n<=10){
        int a=Integer.parseInt(TXTIdInscripcion.getText());
        Inscripcion ins=id.buscarInscripcion(a);
        ins.setNota(n);
        id.actualizarInscripcion(ins);
        JOptionPane.showMessageDialog(this, "Calificacion guardada");

        }else{
            JOptionPane.showMessageDialog(this, "por favor ingrese una calificacion menor a 10");
        }
    }//GEN-LAST:event_BCalificacionActionPerformed

    private void TXTCalificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTCalificacionKeyTyped
        // TODO add your handling code here:
        char digito = evt.getKeyChar();
        if(!Character.isDigit(digito)&&digito!='.'){
            evt.consume();
        }

    }//GEN-LAST:event_TXTCalificacionKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InscripcionCalificacionVistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InscripcionCalificacionVistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InscripcionCalificacionVistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InscripcionCalificacionVistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InscripcionCalificacionVistas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCalificacion;
    private javax.swing.JComboBox<String> CBInscripcion;
    private javax.swing.JTextField TXTAlumno;
    private javax.swing.JTextField TXTCalificacion;
    private javax.swing.JTextField TXTIdInscripcion;
    private javax.swing.JTextField TXTMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
